# Interview Questions {#interviewquestions}

## Intact Senior Data Scientist Questions for Technical Test

There will be three coding questions and eleven on machine learning and statistics.

The coding questions:
1. Vector Compression
2. Cross Validation
3. Bag of words features

Q 1.0. What is vector compression?

Attempt 1: Not sure what is vector compression, but I know what is list comprehension. It is a method to write a for loop in one line. It can have conditional statements as well. 

 

Q 2.0. Describe cross-validation and when is it done and when not to do it.

K-fold cross-validation is a technique to partition the data into several chunks and rotating through them for training and testing the model. For K-fold cross validation the data is separated into k non-overlapping (mutually exclusive) partitions of equal size. The data in all partitions except the first partition is used to training the model and the data left out is used to test the model. We do this again, but now use all the data except in the second partition for training and the data in the second partition is used for testing. We do this until we rotate through all the data using each partition only once for testing. At the end, we combine the trained k-models into our final model.

Q 2.1. Implement 10-fold cross-validation in python on a simple machine learning algorithm. 

Q 2.2. Generalize 10-fold CV python implementation into k-fold CV implementation. Allow the user to choose the input using the `input()` function in python for the number of folds to perform and the python code should be able to implement it.

Q 3.0. What is bag of words features?



Q 3.1. Implement this in python.

Implementing bag of words in python. 



The theoretical machine learning questions

The topics will include Clustering, A/B testing, DT(?)

Perhaps she also mentioned random forest.

### Check on Glassdoors to see if there are any questions available there.

1. The questions are not quite hard, which will cover from python to simple algorithm in machine learning. 

2. I think mine has something in NLP.

Questions I have thought up for NLP
2.1. What is wordtovec?
2.2. What is bag of words?
2.3. What are the main algorithms of NLP?
2.4. What do the different NLP algorithms do? What is their aim.

3. How to improve the performance of your model?

4. Describe your previous projects.

5. statistics and machine learning theory questions & use case scenarios of real projects.

6. Cross validation, overfitting, python programing.

7. Why did you choose to apply for Intact?

- The position and type of work.

8. They ask me mostly about modelling

9.1. How do you manage stress and pressure when you have a lot to do in different projects? Give an example.

9.2 Name one time you came up with a creative solution to a problem.

9.3 What is a good service to you? As in customer service. Give an example.

9.4 What data science technology you think has the potential to change the world and in what field?









## Amazon Data Science Questions.

Amazon Leadership Principals

1. __Customer Obsession__
Are obsessed with the customer. Think how can we serve the customer and then think backward.

2. Ownership
You do not sacrifice long term success for short term gains. Also, they think beyond just their task, job, and team but think of the success of the company as a whole. Finally, they never say "that's not my job."

3. Innovate, Invent, and Simplify
Leaders innovate, invent, and simplify. They are externally aware, look for new ideas from everywhere, and are not limited by "not invented here", not done by us. As we do new things, we accept that we may be misunderstood for long periods of time, and since we are trying new things we might be misunderstanding something for long periods of time before correctly understand what is the best way to it.

4. Are Right, A Lot
5. Learn and Be Curious
6. Hire and Develop the Best

7. Insist on the Highest Standards
8. Think Big
9. Bias for Action
10. Frugality
11. Earn Trust
12. Dive Deep
13. Have a Backbone; Disagree and Commit
14. Deliver Results
15. Strive to be Earth's Best Employer
16. Success and Scale Bring Broad Responsibility



Dive deep into the following topics through discussion of your past and current experiences: 

- Estimation and hypothesis testing.

- Regression

- Experiments

- Casual Inference

- Forecasting models

- Time Series forecasting

Machine Learning Knowledge:

Talk about the following machine learning topics:

- Basic machine learning models
- Supervised vs unsupervised learning
_ Bias-Variance tradeoff
- Boosting
- Decision trees
- Different loss functions
- Cross-Validation
- Use of logistic regression for classification
- Others TBA

Link: https://www.glassdoor.ca/Interview/Amazon-Data-Scientist-Interview-Questions-EI_IE6036.0,6_KO7,21_IP2.htm?filter.jobTitleFTS=Data+Scientist

Question curated from Glassdoors on 2022-07-02.

- Can you write SQL and Python.

- What do you do in your current position?

- Do you have experience with data tokenization?

- How would you deal with an imbalanced dataset?

- Explain one of several unsupervised learning algorithms.

- Explain random forest, discuss its pros and cons.

- How to interpret OLS Regression output?

- Explain confidence intervals.

Attempt 1: A confidence interval is associated with confidence level. If the confidence level of the confidence interval is 95%, then you can think about confidence interval as the range that will will capture the correct value of the parameter about 95 times if the same experiment was repeated 100 times.

- Diff techniques to assess multicollinearity (correlation, VIF, tolerance etc)

- Explain unsupervised learning techniques which do not involve clustering

- How to decide k value in KNN

- Explain p-value

Attempt 1: The p-value is a location parameter. It tells you have far your data is from the null hypothesis. The smaller the p-value the farther the data or the sample is from the null hypothesis. 

- To write a query from a table using Group By statement.

Review 1 - Accepted Offer - Positive Experience - Average Interview

There were 3 rounds : first, a general resume based. Second, machine learning related basic questions, and third was the live coding round on python and SQL. Each round consist of 2-3 leadership principles questions towards the end.

1. How to decide k value in KNN
2. Explain unsupervised learning techniques which do not involve clustering
3. Diff techniques to assess multicollinearity (correlation, VIF, tolerance etc)

Review 2 - Accepted Offer - Positive Experience - Average Interview

The whole process took 2+ months.
I applied online for L4 and was contacted by the recruiter the next day. I was scheduled a phone screen interview. Upon passing that I was scheduled an Amazon loop interview consisting for 5 interviews back-to-back. After about 5 days I was notified that I passed and was upgraded to L5. A week after that I was matched with my future team and sent an offer, which I accepted.
Throughout the whole process the recruiter acted professional and kept me updated at each step. The team was very friendly. Overall, the best interview experience I'd had.

"Tell me about the time..." questions.
SQL easy to medium questions.
How to interpret OLS Regression output?
Explain confidence intervals.
Business acumen kind of questions.

Review 3 - N O - P E - A I

It was basically total four round,
1) Resume Verification : Internship, Good Project on Machine Learning or Deep Learning
2) Technical Round: Basic ML Algorithms and math behind them
3) Coding Round: Python or SQL
4) HR Round



## Data Science in Cyber Security

### Cyber Security

Links online to articles:

https://www.securityroundtable.org/the-growing-role-of-machine-learning-in-cybersecurity/

https://medium.com/cyberdefendersprogram/python-for-cybersecurity-lesson-3-data-analysis-with-pandas-501441e14fe0

https://towardsdatascience.com/applying-data-science-to-cybersecurity-network-attacks-events-219fb6312f54

__Data Science for Cybersecurity Course__: https://sites.google.com/view/mikehsiao/teaching/data-science-for-cybersecurity-2022

https://www.worldscientific.com/worldscibooks/10.1142/q0167#t=toc

__Very good talk__: https://www.youtube.com/watch?v=SmDL7t6UQk0&ab_channel=DataScienceDojo

__GitHub repo of Book on Machine Learning for Cyber Security: __ https://github.com/wtsxDev/Machine-Learning-for-Cyber-Security

__Kaggle challenge__: https://www.kaggle.com/datasets/mohamedamineferrag/edgeiiotset-cyber-security-dataset-of-iot-iiot

__A curated list of amazingly awesome tools and resources related to the use of machine learning for cyber security.__

This has:

-Datasets
-Papers
-Books
-Talks
-Tutorials
-Courses
-Miscellaneous

Link: https://github.com/jivoi/awesome-ml-for-cybersecurity

__Course lectures of DS4CS: __ https://www.youtube.com/watch?v=YzRjY4f_-tM&list=PL_ExBw9oE-6iHE31yoeZ_5HgaCsgpyMtk&index=1&ab_channel=%E8%95%AD%E8%88%9C%E6%96%87



Cyber security has a red team and a blue team. The red team offensive testing. Blue team defensive testing.

Look into machine learning for red team and blue team. 

Continuous Monitoring in software development. 
5 Types of Monitoring + Cyber Security Monitoring.




Blue team blocks the red team using automation. 



Cloud flare, bulletproof security. 

Big cyber security companies using Sophos, Solar Events.

Data is very important in both CS and DS. 

Understand what port is, what is a packet? 

Need to understand networking, and internet protocol. Understand basics of linux.

### Splunk Training







## Important Ideas and Interview Questions

__Q1. What is the difference between between random forest and xgboost?__

In random forest we grow trees randomly and independently of one another. In fact it is a requirement that the trees are independent. At the end, the predictions from all the trees are averaged to give the final prediction value of the random forest algorithm.

XGboost grows the trees sequentially, with every new tree minimizing the error of the previous tree, hence, creating a sequence of trees that try to fit what the previous trees were not able to fit well. At the end, the predictions from all the trees are averaged to get the final prediction value of the XGboost algorithm.

For tabular data, in general, XGboost tends to always outperform every other machine learning algorithm, including random forest, for predictions.

__Q2. What is the difference between bias and variance and what is the trade-off?__

Bias is how much your data is systematically off. 

Bias: Measurements that are systematically off-target, or sample is not representative of population of interest. Observational studies are especially vulnerable to it. Why?

__Q3. What is NoSQL?__

__Q4. What is GraphSQL?__

__Q5. What is the difference between NoSQL and SQL?__


